import { Poppins } from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber/Navber";
import NextAuthProvider from "./providers/nextAuthProvider";


const poppins = Poppins({
  weight: ['400', '600', "700"],
  subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthProvider>

      <body
        className={`${poppins.className} antialiased`}
        >
        <Navber/>
        {children}
      </body>
        </NextAuthProvider>
    </html>
  );
}
